// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

extern int progress_01;

void refreshScreen(lv_event_t * e)
{
	if(progress_01 < 95)
  {
    progress_01 += 5;
  }
  else
  {
    progress_01 = 0;
  }
}
